prog @n ::= expr eof ;

expr ::= term { ( "+" | "-" ) term } ;
term ::= factor { ( "*" | "/" ) factor } ;
factor ::= number | identifier | group ;
group @x ::= oparen expr cparen ;
oparen @xw ::= "(" ;
cparen @xw ::= ")" ;

identifier @cxw ::= letter { letter | digit | "_" } ;
number @cwx ::= digit { digit } ;
